version: '3.7'
services:
  mysqldb:
    image: mysql:8.0
    volumes:
      - ./src/test/resources:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=base
      - MYSQL_USER=adm
      - MYSQL_PASSWORD=9mRE